-- PostgreSQL schema for Hotel Booking app (Supabase)
-- All primary keys use integer identity (auto-increment)

-- Enable required extensions (run in Supabase SQL editor if needed)
-- CREATE EXTENSION IF NOT EXISTS postgis;


-- 1. Core user & role tables

CREATE TABLE users (
    id              uuid references auth.users not null primary key,
    full_name       TEXT        NOT NULL,
    avatar_url      TEXT        NOT NULL,
    is_active       BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE roles (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    TEXT    NOT NULL UNIQUE
);

CREATE TABLE users_roles (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id  INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    UNIQUE (user_id, role_id)
);

-- tạo hàm thêm dữ liệu vào bảng public.users, public.users_roles khi thêm mới users
create or replace function public.handle_new_user()
returns trigger as $$
declare
  role_id int;
  user_role_name text;
begin
  -- 1. Lấy tên role từ metadata truyền từ App (mặc định là CUSTOMER nếu không truyền)
  user_role_name := coalesce(new.raw_user_meta_data->>'role', 'CUSTOMER');

  -- 2. Chèn vào bảng profiles (Thông tin cơ bản)
  insert into public.users (id, full_name, avatar_url)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', 'Người dùng mới'),
    coalesce(new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'picture', null)
  );

  -- 3. Lấy id của role từ bảng roles dựa trên tên (CUSTOMER, HOST, v.v.)
  select id into role_id from public.roles where name = user_role_name;

  -- 4. Chèn vào bảng trung gian users_roles
  if role_id is not null then
    insert into public.users_roles (user_id, role_id)
    values (new.id, role_id);
  end if;

  return new;
end;
$$ language plpgsql security definer;

-- 2. Location master data (Vietnam provinces / districts / wards)

CREATE TABLE provinces (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code    TEXT    NOT NULL UNIQUE,
    name    TEXT    NOT NULL
);

CREATE TABLE districts (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    province_id  INTEGER NOT NULL REFERENCES provinces(id) ON DELETE CASCADE,
    code         TEXT    NOT NULL,
    name         TEXT    NOT NULL,
    UNIQUE (province_id, code)
);

CREATE TABLE wards (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    district_id  INTEGER NOT NULL REFERENCES districts(id) ON DELETE CASCADE,
    code         TEXT    NOT NULL,
    name         TEXT    NOT NULL,
    UNIQUE (district_id, code)
);


-- 3. Hotels

CREATE TABLE hotels (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT        NOT NULL,
    description     TEXT,
    host_id         uuid     REFERENCES users(id) ON DELETE SET NULL,
    province_id   INTEGER REFERENCES provinces(id) ON DELETE SET NULL,
    district_id   INTEGER REFERENCES districts(id) ON DELETE SET NULL,
    ward_id         INTEGER REFERENCES wards(id) ON DELETE SET NULL,
    street          TEXT,
    base_currency   CHAR(3)     NOT NULL DEFAULT 'VND',
    is_active       BOOLEAN     NOT NULL DEFAULT TRUE,
    longitude       DOUBLE PRECISION,
    latitude        DOUBLE PRECISION,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_hotels_location_codes
    ON hotels (province_id, district_id, ward_id);


-- 4. Room types

CREATE TABLE room_types (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id             INTEGER NOT NULL REFERENCES hotels(id) ON DELETE CASCADE,
    name                 TEXT    NOT NULL,
    description          TEXT,
    max_guests           INTEGER NOT NULL,
    bed_count            INTEGER NOT NULL,
    bed_type             TEXT,
    base_price_per_night NUMERIC(10,2) NOT NULL,
    has_free_cancellation BOOLEAN NOT NULL DEFAULT FALSE,
    is_active            BOOLEAN NOT NULL DEFAULT TRUE,
    quantity             INTEGER NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_room_types_hotel
    ON room_types (hotel_id);


-- 5. Facilities

CREATE TABLE facility_types (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    TEXT    NOT NULL UNIQUE
);

CREATE TABLE facilities (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_type_id INTEGER NOT NULL REFERENCES facility_types(id) ON DELETE CASCADE,
    name             TEXT    NOT NULL
);

-- Junction table: which facilities a hotel offers
CREATE TABLE hotel_facilities (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id     INTEGER NOT NULL REFERENCES hotels(id) ON DELETE CASCADE,
    facility_id  INTEGER NOT NULL REFERENCES facilities(id) ON DELETE CASCADE,
    UNIQUE (hotel_id, facility_id)
);

CREATE INDEX idx_hotel_facilities_hotel
    ON hotel_facilities (hotel_id);


-- 6. Policies

CREATE TABLE policy_types (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code    TEXT    NOT NULL UNIQUE,
    name    TEXT    NOT NULL
);

CREATE TABLE policies (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id        INTEGER NOT NULL REFERENCES hotels(id) ON DELETE CASCADE,
    policy_type_id  INTEGER NOT NULL REFERENCES policy_types(id) ON DELETE RESTRICT,
    title           TEXT,
    content         TEXT,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_policies_hotel
    ON policies (hotel_id);


-- 7. Images

CREATE TABLE images (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id     INTEGER NOT NULL REFERENCES hotels(id) ON DELETE CASCADE,
    room_type_id INTEGER REFERENCES room_types(id) ON DELETE SET NULL,
    url          TEXT    NOT NULL,
    is_cover     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_images_hotel
    ON images (hotel_id);


-- 8. Booking statuses


CREATE TYPE booking_status_enum AS ENUM ('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED');

-- 9. Bookings & booked rooms
CREATE TYPE payment_status_enum AS ENUM ('UNPAID', 'PAID');

CREATE TABLE bookings (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_code    TEXT        NOT NULL UNIQUE,
    customer_id     uuid     NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    hotel_id        INTEGER     NOT NULL REFERENCES hotels(id) ON DELETE RESTRICT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    checkin_date    DATE        NOT NULL,
    checkout_date   DATE        NOT NULL,
    num_adults      INTEGER     NOT NULL,
    num_children    INTEGER     NOT NULL DEFAULT 0,
    total_amount    NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    currency        CHAR(3)     NOT NULL DEFAULT 'VND',
    status_code     booking_status_enum        NOT NULL  DEFAULT 'PENDING',
    payment_status  payment_status_enum        NOT NULL  DEFAULT 'UNPAID',
    payment_method  TEXT        NOT NULL DEFAULT 'CASH'
);

CREATE INDEX idx_bookings_customer
    ON bookings (customer_id);

CREATE INDEX idx_bookings_hotel
    ON bookings (hotel_id);

CREATE INDEX idx_bookings_dates
    ON bookings (checkin_date, checkout_date);


CREATE TABLE booked_rooms (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id      INTEGER NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    room_type_id    INTEGER NOT NULL REFERENCES room_types(id) ON DELETE RESTRICT,
    room_id         INTEGER,
    quantity        INTEGER NOT NULL,
    price_per_night NUMERIC(10,2) NOT NULL,
    nights          INTEGER NOT NULL,
    subtotal        NUMERIC(10,2) NOT NULL
);

CREATE INDEX idx_booked_rooms_booking
    ON booked_rooms (booking_id);


-- 10. Reviews

CREATE TABLE reviews (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id   INTEGER NOT NULL UNIQUE REFERENCES bookings(id) ON DELETE CASCADE,
    hotel_id     INTEGER NOT NULL REFERENCES hotels(id) ON DELETE CASCADE,
    customer_id  uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    rating       INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment      TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_reviews_hotel
    ON reviews (hotel_id);

CREATE INDEX idx_reviews_customer
    ON reviews (customer_id);


-- 11. Favorites (liked hotels)

CREATE TABLE favorites (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    hotel_id     INTEGER NOT NULL REFERENCES hotels(id) ON DELETE CASCADE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (customer_id, hotel_id)
);

CREATE INDEX idx_favorites_customer
    ON favorites (customer_id);

CREATE INDEX idx_favorites_hotel
    ON favorites (hotel_id);
