-- PostgreSQL schema for Hotel Booking app (Supabase)
-- All primary keys use integer identity (auto-increment)

-- Enable required extensions (run in Supabase SQL editor if needed)
-- CREATE EXTENSION IF NOT EXISTS postgis;


-- 1. Core user & role tables

CREATE TABLE users (
    id              uuid REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    email           varchar(255) not null unique,
    phone           varchar(20) ,
    full_name       TEXT        NOT NULL,
    avatar_url      TEXT        NOT NULL,
    is_active       BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE roles (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    TEXT    NOT NULL UNIQUE
);

CREATE TABLE users_roles (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id  INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    UNIQUE (user_id, role_id)
);
-- tạo hàm thêm dữ liệu vào bảng public.users, public.users_roles khi thêm mới users
create or replace function public.handle_new_user()
returns trigger as $$
declare
  role_id int;
  user_role_name text;
begin
  -- 1. Lấy tên role từ metadata truyền từ App (mặc định là CUSTOMER nếu không truyền)
  user_role_name := coalesce(new.raw_user_meta_data->>'role', 'CUSTOMER');

  -- 2. Chèn vào bảng profiles (Thông tin cơ bản)
  insert into public.users (id, full_name, avatar_url, email, phone)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', 'Người dùng mới'),
    coalesce(new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'picture', 'https://tjsycqpwxutseencwlzr.supabase.co/storage/v1/object/sign/btl-android-n7/avatar/default-avatar.webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81ZTcyYmI2Mi05OGFjLTRlN2EtYmFmMi02ZjVkMDgxMTUyOWYiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJidGwtYW5kcm9pZC1uNy9hdmF0YXIvZGVmYXVsdC1hdmF0YXIud2VicCIsImlhdCI6MTc3NDA4MTY2NCwiZXhwIjoxODA1NjE3NjY0fQ.suQGhX4qE7sQp39RxL_n7alTf6L_UVAfNagpfbzMq1E'),
    coalesce(new.raw_user_meta_data->>'email', new.email),
    coalesce(new.raw_user_meta_data->>'phone', new.phone)
  );

  -- 3. Lấy id của role từ bảng roles dựa trên tên (CUSTOMER, HOST, v.v.)
  select id into role_id from public.roles where name = user_role_name;

  -- 4. Chèn vào bảng trung gian users_roles
  if role_id is not null then
    insert into public.users_roles (user_id, role_id)
    values (new.id, role_id);
  end if;

  return new;
end;
$$ language plpgsql security definer;

-- 2. Location master data (Vietnam provinces / districts / wards)

CREATE TABLE provinces (
    code VARCHAR(20) NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    name_en VARCHAR(255),
    full_name VARCHAR(255) NOT NULL
);

-- Create the districts table
CREATE TABLE districts (
    code VARCHAR(20) NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    name_en VARCHAR(255),
    full_name VARCHAR(255) NOT NULL,
    province_code VARCHAR(20) NOT NULL,
    CONSTRAINT fk_province
        FOREIGN KEY(province_code)
        REFERENCES provinces(code)
        ON DELETE CASCADE
);

-- Create an index for faster lookups by province_code
CREATE INDEX idx_districts_province_code ON districts(province_code);

-- Create the wards table
CREATE TABLE wards (
    code VARCHAR(20) NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    name_en VARCHAR(255),
    full_name VARCHAR(255) NOT NULL,
    district_code VARCHAR(20) NOT NULL,
    CONSTRAINT fk_district
        FOREIGN KEY(district_code)
        REFERENCES districts(code)
        ON DELETE CASCADE
);

-- Create an index for faster lookups by district_code
CREATE INDEX idx_wards_district_code ON wards(district_code);


-- 3. Hotels

CREATE TABLE hotels (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT        NOT NULL,
    description     TEXT,
    host_id         uuid     REFERENCES users(id) ON DELETE SET NULL,
    province_code varchar(20) references provinces(code) on delete set null,
    district_code varchar(20) references districts(code) on delete set null,
    ward_code varchar(20) references wards(code) on delete set null,
    street          TEXT,
    base_currency   CHAR(3)     NOT NULL DEFAULT 'VND',
    is_active       BOOLEAN     NOT NULL DEFAULT TRUE,
    longitude       DOUBLE PRECISION,
    latitude        DOUBLE PRECISION,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_hotels_location_codes
    ON hotels (province_code, district_code, ward_code);


-- 4. Room types

CREATE TABLE room_types (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id             INTEGER NOT NULL REFERENCES hotels(id) ON DELETE CASCADE,
    name                 TEXT    NOT NULL,
    description          TEXT,
    max_guests           INTEGER NOT NULL,
    bed_count            INTEGER NOT NULL,
    bed_type             TEXT,
    base_price_per_night NUMERIC(10,2) NOT NULL,
    has_free_cancellation BOOLEAN NOT NULL DEFAULT FALSE,
    is_active            BOOLEAN NOT NULL DEFAULT TRUE,
    quantity             INTEGER NOT NULL DEFAULT 0,
    view                 TEXT,
    area                 INTEGER,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_room_types_hotel
    ON room_types (hotel_id);


-- 5. Facilities

CREATE TABLE facility_types (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    TEXT    NOT NULL UNIQUE,
    name_vi TEXT NOT NULL
);

CREATE TABLE facilities (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_type_id INTEGER NOT NULL REFERENCES facility_types(id) ON DELETE CASCADE,
    name             TEXT    NOT NULL,
    name_vi          TEXT    NOT NULL
);

-- Junction table: which facilities a hotel offers
CREATE TABLE hotel_facilities (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id     INTEGER NOT NULL REFERENCES hotels(id) ON DELETE CASCADE,
    facility_id  INTEGER NOT NULL REFERENCES facilities(id) ON DELETE CASCADE,
    UNIQUE (hotel_id, facility_id)
);

CREATE INDEX idx_hotel_facilities_hotel
    ON hotel_facilities (hotel_id);


-- 6. Policies

CREATE TABLE policy_types (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code    TEXT    NOT NULL UNIQUE,
    name    TEXT    NOT NULL
);

CREATE TABLE policies (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id        INTEGER NOT NULL REFERENCES hotels(id) ON DELETE CASCADE,
    policy_type_id  INTEGER NOT NULL REFERENCES policy_types(id) ON DELETE RESTRICT,
    title           TEXT,
    content         TEXT,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_policies_hotel
    ON policies (hotel_id);


-- 7. Images

CREATE TABLE images (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id     INTEGER NOT NULL REFERENCES hotels(id) ON DELETE CASCADE,
    room_type_id INTEGER REFERENCES room_types(id) ON DELETE SET NULL,
    url          TEXT    NOT NULL,
    is_cover     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_images_hotel
    ON images (hotel_id);


-- 8. Booking statuses


CREATE TYPE booking_status_enum AS ENUM ('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'REJECTED', 'NO_SHOW', 'CHECKED_IN');

-- 9. Bookings & booked rooms
CREATE TYPE payment_status_enum AS ENUM ('UNPAID', 'PAID');

CREATE TABLE bookings (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_code    TEXT        NOT NULL UNIQUE,
    customer_id     uuid     NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    customer_fullname varchar(255),
    customer_email varchar(255),
    customer_phone varchar(20),
    hotel_id        INTEGER     NOT NULL REFERENCES hotels(id) ON DELETE RESTRICT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    checkin_date    DATE        NOT NULL,
    checkout_date   DATE        NOT NULL,
    num_adults      INTEGER     NOT NULL,
    num_children    INTEGER     NOT NULL DEFAULT 0,
    total_amount    NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    currency        CHAR(3)     NOT NULL DEFAULT 'VND',
    special_requirement text,
    status_code     booking_status_enum        NOT NULL  DEFAULT 'PENDING',
    payment_status  payment_status_enum        NOT NULL  DEFAULT 'UNPAID',
    payment_method  TEXT        NOT NULL DEFAULT 'CASH'
);

CREATE INDEX idx_bookings_customer
    ON bookings (customer_id);

CREATE INDEX idx_bookings_hotel
    ON bookings (hotel_id);

CREATE INDEX idx_bookings_dates
    ON bookings (checkin_date, checkout_date);


CREATE TABLE booked_rooms (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id      INTEGER NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    room_type_id    INTEGER NOT NULL REFERENCES room_types(id) ON DELETE RESTRICT,
    quantity        INTEGER NOT NULL,
    price_per_night NUMERIC(10,2) NOT NULL,
    nights          INTEGER NOT NULL,
    subtotal        NUMERIC(10,2) NOT NULL
);

CREATE INDEX idx_booked_rooms_booking
    ON booked_rooms (booking_id);


-- 10. Reviews

CREATE TABLE reviews (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id   INTEGER NOT NULL UNIQUE REFERENCES bookings(id) ON DELETE CASCADE,
    hotel_id     INTEGER NOT NULL REFERENCES hotels(id) ON DELETE CASCADE,
    customer_id  uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    rating       INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 10),
    comment      TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_reviews_hotel
    ON reviews (hotel_id);

CREATE INDEX idx_reviews_customer
    ON reviews (customer_id);


-- 11. Favorites (liked hotels)

CREATE TABLE favorites (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    hotel_id     INTEGER NOT NULL REFERENCES hotels(id) ON DELETE CASCADE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (customer_id, hotel_id)
);

CREATE INDEX idx_favorites_customer
    ON favorites (customer_id);

CREATE INDEX idx_favorites_hotel
    ON favorites (hotel_id);

insert into public.roles (name) values ('CUSTOMER'), ('HOST'), ('ADMIN');

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 1. Cấp quyền truy cập (Usage) vào schema public
grant usage on schema public to authenticated;
grant usage on schema public to anon;

-- 2. Cấp quyền thao tác trên tất cả các bảng hiện có trong schema public
grant all privileges on all tables in schema public to authenticated;
grant all privileges on all sequences in schema public to authenticated;

grant select on table provinces to anon, service_role;
grant select on table districts to anon, service_role;
grant select on table wards to anon, service_role;
grant select on table facilities to anon, service_role;
grant select on table facility_types to anon, service_role;
grant select on table bookings to anon, service_role;
REVOKE SELECT ON TABLE bookings FROM anon;
grant all privileges on all tables in schema public to anon;

grant all privileges on all tables in schema public to service_role;
-- 3. Đảm bảo các bảng tạo trong tương lai cũng tự động cấp quyền
alter default privileges in schema public grant all on tables to authenticated;

-- 1. Grant usage on the schema to all relevant roles
GRANT USAGE ON SCHEMA public TO postgres, anon, authenticated, service_role;



alter table public.facility_types
add column name_vi text;
insert into public.facility_types (name, name_vi)
values  ('Bathroom', 'Phòng tắm'),
        ('Bedroom', 'Phòng ngủ'),
        ('Food & Drink', 'Ăn uống'),
        ('Outdoors', 'Ngoài trời'),
        ('Activity', 'Hoạt động'),
        ('Living area', 'Phòng khách'),
        ('Media & Tech', 'Truyền thông & Công nghệ'),
        ('Internet', 'Internet'),
        ('Parking', 'Đỗ xe'),
        ('Reception', 'Lễ tân'),
        ('Cleaning', 'Dọn dẹp'),
        ('Safety & Security', 'An ninh'),
        ('Wellness', 'Chăm sóc sức khoẻ'),
        ('Accessibility', 'Hỗ trợ người khuyết tật'),
        ('Language', 'Ngôn ngữ được sử dụng');

alter table facilities
add column name_vi text;
delete from public.facility_types;

insert into public.facility_types (name, name_vi)
values  ('Bathroom', 'Phòng tắm'),
        ('Bedroom', 'Phòng ngủ'),
        ('Outdoors', 'Ngoài trời'),
        ('Kitchen', 'Nhà bếp'),
        ('Media & Tech', 'Truyền thông & Công nghệ'),
        ('Food & Drink', 'Ăn uống'),
        ('Swimming Pool', 'Hồ bơi'),
        ('Wellness & Spa', 'Sức khỏe & Spa'),
        ('Activity', 'Hoạt động'),
        ('Reception', 'Lễ tân'),
        ('Cleaning', 'Dọn dẹp'),
        ('Safety & Security', 'An ninh'),
        ('General', 'Tiện ich chung'),
        ('Accessibility', 'Hỗ trợ người khuyết tật'),
        ('Parking', 'Đỗ xe');

-- facilities (id, facility_type_id, name,name_vi)

-- Facilities for 'Bathroom' (facility_type_id = 1)
INSERT INTO facilities (facility_type_id, name, name_vi) VALUES
(1, 'Private bathroom', 'Phòng tắm riêng'),
(1, 'Shower', 'Vòi sen'),
(1, 'Bathtub', 'Bồn tắm'),
(1, 'Free toiletries', 'Đồ vệ sinh cá nhân miễn phí'),
(1, 'Hairdryer', 'Máy sấy tóc'),
(1, 'Towels', 'Khăn tắm'),
(1, 'Slippers', 'Dép đi trong nhà'),
(1, 'Toilet paper', 'Giấy vệ sinh');

-- Facilities for 'Bedroom' (facility_type_id = 2)
INSERT INTO facilities (facility_type_id, name, name_vi) VALUES
(2, 'Linen', 'Ga trải giường'),
(2, 'Wardrobe', 'Tủ quần áo'),
(2, 'Air conditioning', 'Điều hòa không khí'),
(2, 'Heating', 'Hệ thống sưởi'),
(2, 'Desk', 'Bàn làm việc'),
(2, 'Soundproofing', 'Cách âm');

-- Facilities for 'Outdoors & View' (facility_type_id = 3)
INSERT INTO facilities (facility_type_id, name, name_vi) VALUES
(3, 'City view', 'Nhìn ra thành phố'),
(3, 'Sea view', 'Nhìn ra biển'),
(3, 'Garden view', 'Nhìn ra vườn'),
(3, 'Pool view', 'Nhìn ra hồ bơi'),
(3, 'Balcony', 'Ban công'),
(3, 'Terrace', 'Sân hiên'),
(3, 'Patio', 'Sân trong'),
(3, 'Outdoor furniture', 'Nội thất ngoài trời');

-- Facilities for 'Kitchen' (facility_type_id = 4)
INSERT INTO facilities (facility_type_id, name, name_vi) VALUES
(4, 'Refrigerator', 'Tủ lạnh'),
(4, 'Microwave', 'Lò vi sóng'),
(4, 'Electric kettle', 'Ấm đun nước điện'),
(4, 'Stovetop', 'Bếp nấu'),
(4, 'Kitchenware', 'Dụng cụ nhà bếp'),
(4, 'Dining table', 'Bàn ăn'),
(4, 'Coffee machine', 'Máy pha cà phê');

-- Facilities for 'Media & Technology' (facility_type_id = 5)
INSERT INTO facilities (facility_type_id, name, name_vi) VALUES
(5, 'Flat-screen TV', 'TV màn hình phẳng'),
(5, 'Cable channels', 'Truyền hình cáp'),
(5, 'Satellite channels', 'Truyền hình vệ tinh'),
(5, 'Telephone', 'Điện thoại'),
(5, 'Streaming service (like Netflix)', 'Dịch vụ streaming (như Netflix)'),
(5, 'Laptop safe', 'Két an toàn cho laptop'),
(5, 'Radio', 'Đài Radio');

-- Facilities for 'Food & Drink' (facility_type_id = 6)
INSERT INTO facilities (facility_type_id, name, name_vi) VALUES
(6, 'Minibar', 'Quầy bar mini'),
(6, 'Room service', 'Dịch vụ phòng'),
(6, 'Bar', 'Quầy bar'),
(6, 'Restaurant', 'Nhà hàng'),
(6, 'Breakfast in the room', 'Bữa sáng tại phòng'),
(6, 'Snack bar', 'Quầy đồ ăn nhẹ'),
(6, 'Wine/champagne', 'Rượu vang/sâm panh');

-- Facilities for 'Swimming Pool' (facility_type_id = 7)
INSERT INTO facilities (facility_type_id, name, name_vi) VALUES
(7, 'Outdoor pool (all year)', 'Hồ bơi ngoài trời (quanh năm)'),
(7, 'Indoor pool', 'Hồ bơi trong nhà'),
(7, 'Rooftop pool', 'Hồ bơi trên sân thượng'),
(7, 'Pool/beach towels', 'Khăn tắm hồ bơi/bãi biển'),
(7, 'Sun loungers or beach chairs', 'Ghế dài tắm nắng'),
(7, 'Pool bar', 'Quầy bar hồ bơi'),
(7, 'Infinity pool', 'Hồ bơi vô cực');

-- Facilities for 'Wellness & Spa' (facility_type_id = 8)
INSERT INTO facilities (facility_type_id, name, name_vi) VALUES
(8, 'Spa and wellness centre', 'Trung tâm spa và chăm sóc sức khỏe'),
(8, 'Fitness centre', 'Trung tâm thể dục'),
(8, 'Sauna', 'Phòng xông hơi'),
(8, 'Massage', 'Mát-xa'),
(8, 'Hot tub/Jacuzzi', 'Bồn tắm nước nóng/Jacuzzi'),
(8, 'Steam room', 'Phòng xông hơi ướt'),
(8, 'Beauty Services', 'Dịch vụ làm đẹp');

-- Facilities for 'Activities' (facility_type_id = 9)
INSERT INTO facilities (facility_type_id, name, name_vi) VALUES
(9, 'Live music/performance', 'Nhạc sống/biểu diễn'),
(9, 'Happy hour', 'Giờ khuyến mãi'),
(9, 'Themed dinner nights', 'Đêm tối theo chủ đề'),
(9, 'Tour or class about local culture', 'Tour/lớp học về văn hóa địa phương'),
(9, 'Bicycle rental', 'Cho thuê xe đạp'),
(9, 'Children''s playground', 'Sân chơi trẻ em'),
(9, 'Games room', 'Phòng chơi game');

-- Facilities for 'Reception Services' (facility_type_id = 10)
INSERT INTO facilities (facility_type_id, name, name_vi) VALUES
(10, '24-hour front desk', 'Lễ tân 24 giờ'),
(10, 'Concierge service', 'Dịch vụ trợ giúp đặc biệt'),
(10, 'Luggage storage', 'Giữ hành lý'),
(10, 'Tour desk', 'Bàn đặt tour'),
(10, 'Currency exchange', 'Thu đổi ngoại tệ'),
(10, 'Private check-in/check-out', 'Nhận/trả phòng riêng'),
(10, 'Invoice provided', 'Cung cấp hóa đơn');

-- Facilities for 'Cleaning Services' (facility_type_id = 11)
INSERT INTO facilities (facility_type_id, name, name_vi) VALUES
(11, 'Daily housekeeping', 'Dọn phòng hàng ngày'),
(11, 'Laundry', 'Giặt ủi'),
(11, 'Dry cleaning', 'Giặt khô'),
(11, 'Ironing service', 'Dịch vụ ủi'),
(11, 'Trouser press', 'Máy là quần'),
(11, 'Shoeshine', 'Đánh giày'),
(11, 'Wake-up service', 'Dịch vụ báo thức');

-- Facilities for 'Safety & Security' (facility_type_id = 12)
INSERT INTO facilities (facility_type_id, name, name_vi) VALUES
(12, '24-hour security', 'An ninh 24 giờ'),
(12, 'Key card access', 'Thẻ khóa điện tử'),
(12, 'Security alarm', 'Báo động an ninh'),
(12, 'Smoke alarms', 'Báo động khói'),
(12, 'CCTV in common areas', 'Camera quan sát ở khu vực chung'),
(12, 'Fire extinguishers', 'Bình chữa cháy'),
(12, 'Safety deposit box', 'Két an toàn');

-- Facilities for 'General' (facility_type_id = 13)
INSERT INTO facilities (facility_type_id, name, name_vi) VALUES
(13, 'Free WiFi', 'WiFi miễn phí'),
(13, 'Non-smoking rooms', 'Phòng không hút thuốc'),
(13, 'Family rooms', 'Phòng gia đình'),
(13, 'Lift', 'Thang máy'),
(13, 'Designated smoking area', 'Khu vực hút thuốc riêng'),
(13, 'Airport shuttle', 'Dịch vụ đưa đón sân bay'),
(13, 'Gift shop', 'Cửa hàng quà tặng');

-- Facilities for 'Accessibility' (facility_type_id = 14)
INSERT INTO facilities (facility_type_id, name, name_vi) VALUES
(14, 'Wheelchair accessible', 'Lối đi cho xe lăn'),
(14, 'Upper floors accessible by elevator', 'Tầng trên có thể đi bằng thang máy'),
(14, 'Toilet with grab rails', 'Nhà vệ sinh có tay vịn'),
(14, 'Lowered sink', 'Bồn rửa thấp'),
(14, 'Emergency cord in bathroom', 'Dây kéo khẩn cấp trong phòng tắm'),
(14, 'Visual aids: Braille', 'Hỗ trợ thị giác: chữ nổi Braille'),
(14, 'Auditory guidance', 'Hướng dẫn bằng âm thanh');

-- Facilities for 'Parking' (facility_type_id = 15)
INSERT INTO facilities (facility_type_id, name, name_vi) VALUES
(15, 'Free private parking', 'Chỗ đỗ xe riêng miễn phí'),
(15, 'On-site parking', 'Chỗ đỗ xe tại chỗ'),
(15, 'Valet parking', 'Dịch vụ đỗ xe hộ'),
(15, 'Secured parking', 'Chỗ đỗ xe an toàn'),
(15, 'Parking garage', 'Nhà để xe'),
(15, 'Electric vehicle charging station', 'Trạm sạc xe điện'),
(15, 'Accessible parking', 'Bãi đậu xe cho người khuyết tật');

create table room_type_facilities(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_type_id     INTEGER NOT NULL REFERENCES room_types(id) ON DELETE CASCADE,
    facility_id  INTEGER NOT NULL REFERENCES facilities(id) ON DELETE CASCADE,
    UNIQUE (room_type_id, facility_id)
);

alter table room_types
add column area integer;
alter table room_types
add column view text;
insert into public.policy_types (code, name)
values ('CHECKIN_CHECKOUT', 'Check-in và Check-out'),
        ('CANCELLATION', 'Huỷ phòng'),
        ('PETS', 'Thú cưng'),
        ('CHILDREN', 'Trẻ em'),
        ('SMOKING', 'Hút thuốc'),
        ('PAYMENT', 'Thanh toán và Đặt cọc'),
        ('EXTRA_BED', 'Giường thêm');

